### PR TITLE
Mobile+markup fixes

### PR DESCRIPTION
**Pull request by toastal**
- set the `<pre>` blocks to overflow (scrollable), because otherwise the elements caused the page to scroll on small screens
- shrink banner text on even small screen; I showed the site to someone via my phone and the name fell off the page
- Index page (no need to fix the files handled by Pandoc because it does smart things)
  - `'` → `&apos;`
  - some quotations move to `<q>`. Others seemed like quotes for emphasis not like quotes or speech so I left them. Maybe those make more sense as single quotation marks for this reason, but probably too pedantic

### CODE REVIEW

**Comment by toastal** [comment]
looks like this needs a commit yanked

**Comment by dmbaturin** [comment]
I used quotes around `"themes"` because their meaning is rather different from the conventional CMSes and SSGs. Proper quotes definitely look better.

I've been wondering about a "smart punctuation for HTML" plugin, but I'm not sure if there's an efficient way to write one.

**Comment by toastal** [comment]
@dmbaturin the `<q>` does do 'smart' quotes when a `lang` tag is set (or at least should according the spec I believe). Did I miss something?

**Comment by dmbaturin** [comment]
Oh, I'm only talking about my motivation for quotes that may look spurious or be interpreted as "scare quotes". :)

**Pull request merged**
